# Generated by Django 5.2.6 on 2025-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ingredientes', models.CharField(max_length=250)),
                ('foto_cardapio', models.ImageField(upload_to='')),
                ('foto_carrossel', models.ImageField(blank=True, upload_to='')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
