classDiagram
    class Prato{
      CharField nome
      CharField ingredientes
      ImageField foto_cardapio
      ImageField foto_carrossel
      DecimalField preco
    }
    class Avaliacao{
      IntegerField nota
      CharField nome_cliente
      CharField resenha
    }
    class Funcionario{
        CharField nome
        CharField funcao
        ImageField foto
    }