classDiagram
    class Prato{
      CharField nome
      CharField ingredientes
      ImageField imagem_cardapio
      ImageField imagem_carrossel
      DecimalField preco
    }
    class Avaliacao{
      IntegerField nota
      CharField nome_cliente
      CharField resenha
    }
    class Promocao{
      ForeignKey id_prato
      IntegerField desconto
    }
    class Funcionario{
        CharField nome
        CharField funcao
        ImageField foto
    }
    Promocao "1" --> Prato