# Generated by Django 5.2.6 on 2025-09-21 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nome_cliente', models.CharField(max_length=30)),
                ('resenha', models.TextField()),
                ('foto_cliente', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('PC', 'Personal Chef'), ('B', 'Buffet'), ('JT', 'Jantar Temático')], max_length=2)),
                ('nome_cliente', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ingredientes', models.CharField(max_length=250)),
                ('foto_cardapio', models.ImageField(upload_to='')),
                ('foto_carrossel', models.ImageField(blank=True, upload_to='')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('adicionar_carrossel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField()),
                ('telefone', models.CharField(max_length=11)),
                ('data', models.DateField()),
                ('horario', models.DateTimeField()),
                ('qtd_pessoas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observacao', models.TextField()),
            ],
        ),
    ]
