# Generated by Django 5.2.6 on 2025-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nome_cliente',
            field=models.CharField(max_length=100),
        ),
    ]
